import json

Q = [
("Kiberxavfsizlik tushunchasi nimani anglatadi?",["Axborot tizimlarini ruxsatsiz kirishdan, hujumlardan va shikastlanishdan himoyalash","Faqat kompyuterlarni viruslardan tozalash","Internet tezligini oshirish","Dasturiy ta'minotni yangilash"],0),
("Axborot xavfsizligining uchta asosiy tamoyili qaysi?",["Konfidensiallik, yaxlitlik, foydalanuvchanlik","Tezlik, ishonchlilik, arzonlik","Shifrlash, autentifikatsiya, avtorizatsiya","Tarmoq, server, ma'lumot"],0),
("Konfidensiallik (maxfiylik) tushunchasi nimani anglatadi?",["Ma'lumotlarning faqat ruxsat etilgan shaxslarga ochiq bo'lishi","Ma'lumotlarning doimo mavjud bo'lishi","Ma'lumotlarning o'zgartirilmasligi","Ma'lumotlarning shifrlangan holda saqlanishi"],0),
("Yaxlitlik (butunlik) tushunchasi nimani anglatadi?",["Ma'lumotlarning ruxsatsiz o'zgartirilmasligini ta'minlash","Ma'lumotlarni faqat ma'lum shaxslar ko'ra olishi","Ma'lumotlarning doimo foydalanish mumkin bo'lishi","Ma'lumotlarning zaxira nusxasi mavjudligi"],0),
("Foydalanuvchanlik (availability) tushunchasi nimani anglatadi?",["Axborot va resurslarning kerakli vaqtda foydalanishga tayyor bo'lishi","Ma'lumotlarni shifrlash imkoniyati","Foydalanuvchilarni identifikatsiya qilish","Tarmoqqa ulanish tezligi"],0),
("Risk tushunchasi kiberxavfsizlikda nimani bildiradi?",["Tahdid va zaiflikning birgalikda keltiradigan ehtimoliy zarari","Faqat viruslar tomonidan keltirilgan zarar","Tarmoq uzilishi ehtimoli","Parolning murakkablik darajasi"],0),
("Tahdid (threat) nima?",["Axborot xavfsizligiga zarar yetkazishi mumkin bo'lgan potensial xavf","Tizimning zaif tomoni","Himoya vositasi","Xavfsizlik siyosati"],0),
("Zaiflik (vulnerability) nima?",["Tizimning tahdidlar tomonidan foydalanilishi mumkin bo'lgan kuchsiz tomoni","Hujum turi","Himoya usuli","Kriptografik algoritm"],0),
("Aktiv (asset) kiberxavfsizlikda nimani bildiradi?",["Tashkilot uchun qiymatga ega bo'lgan axborot yoki resurs","Hujumchining foydalanish vositasi","Xavfsizlik duvori","Tarmoq protokoli"],0),
("Hujumchi kabi fikrlash (attacker mindset) nima uchun muhim?",["Tizimning zaif tomonlarini topish va ularni oldindan bartaraf etish uchun","Hujum qilishni o'rganish uchun","Boshqa hujumchilarni topish uchun","Virus yaratish uchun"],0),
("Tizimli fikrlash kiberxavfsizlikda qanday ahamiyatga ega?",["Barcha xavfsizlik komponentlarini yaxlit tizim sifatida ko'rib chiqish imkonini beradi","Faqat bitta komponentni himoyalashga yordam beradi","Dasturlash tillarini o'rganishga yordam beradi","Tarmoq tezligini oshirishga imkon beradi"],0),
("Boshqarish vositasi (control) kiberxavfsizlikda nima?",["Riskni kamaytirish uchun qo'llaniladigan himoya choralari","Kompyuterni boshqarish dasturi","Ma'lumotlar bazasi","Operatsion tizim"],0),
("Risk darajasi qanday aniqlanadi?",["Tahdid ehtimoli va keltiradigan zarar miqdorining ko'paytmasi orqali","Faqat zarar miqdori bo'yicha","Faqat hujum soni bo'yicha","Foydalanuvchilar soni bo'yicha"],0),
("Risk matritsasi nima?",["Risklarni ehtimollik va ta'sir darajasiga ko'ra tasniflash vositasi","Ma'lumotlar bazasi jadvali","Shifrlash algoritmi","Tarmoq diagrammasi"],0),
("Risklarni boshqarishning asosiy bosqichlari qaysi?",["Aniqlash, baholash, qayta ishlash, monitoring","Shifrlash, saqlash, uzatish","O'rnatish, sozlash, ishga tushirish","Hujum, himoya, tekshirish"],0),
("Risklarni qabul qilish strategiyasi nimani anglatadi?",["Risk mavjudligini tan olish va uni kamaytirishga sarflanmaydigan holat","Riskni boshqa tashkilotga o'tkazish","Riskni to'liq bartaraf etish","Riskni e'tiborsiz qoldirish"],0),
("Risklarni boshqa tashkilotga o'tkazish qanday amalga oshiriladi?",["Sug'urta polisi sotib olish orqali","Ma'lumotlarni o'chirish orqali","Parollarni o'zgartirish orqali","Tarmoqni o'chirish orqali"],0),
("RMIS (Risk Management Information Systems) nima?",["Risklarni boshqarish axborot tizimlari","Tarmoq xavfsizligi protokoli","Shifrlash standarti","Autentifikatsiya usuli"],0),
("Risk chastotasi nimani ko'rsatadi?",["Ma'lum vaqt oralig'ida risk hodisasining sodir bo'lish tezligini","Riskdan keladigan zarar miqdorini","Himoya vositalarining sonini","Foydalanuvchilar sonini"],0),
("Risklarni kamaytirish strategiyasi nimani nazarda tutadi?",["Himoya choralari qo'llash orqali risk ehtimoli yoki ta'sirini pasaytirish","Riskni butunlay yo'q qilish","Riskni e'tiborsiz qoldirish","Tizimni o'chirish"],0),
("Risklarni boshqarishda muhim ko'rsatkichlar (KRI) nima?",["Risk holatini kuzatib borish uchun ishlatiladigan o'lchov mezonlari","Shifrlash kalitining uzunligi","Tarmoq tezligining o'lchovi","Ma'lumotlar bazasining hajmi"],0),
("Risklarni boshqarish freymvorki nima?",["Risklarni tizimli ravishda boshqarish uchun belgilangan yondashuv va qoidalar to'plami","Dasturlash tili","Operatsion tizim","Ma'lumotlar bazasi"],0),
("Risk baholashda sifat (kvalitativ) usuli nimani nazarda tutadi?",["Risklarni yuqori, o'rta, past kabi toifalarga bo'lish","Riskni aniq raqamlar bilan hisoblash","Risklarni avtomatik aniqlash","Risklarni dasturiy ta'minot orqali boshqarish"],0),
("Risk baholashda miqdor (kvantitativ) usuli nimani nazarda tutadi?",["Riskni aniq pul yoki raqam ko'rsatkichlari bilan hisoblash","Risklarni yuqori va past deb baholash","Faqat texnik mutaxassislar fikriga tayanish","Riskni e'tiborsiz qoldirish"],0),
("Ichki kiberjinoyat nima?",["Tashkilot ichidagi xodim tomonidan sodir etiladigan kiberjinoyat","Internet orqali tashqaridan qilingan hujum","Davlat tomonidan amalga oshirilgan hujum","Viruslar orqali tarqalgan jinoyat"],0),
("Tashqi kiberjinoyat nima?",["Tashkilot tashqarisidagi shaxslar tomonidan sodir etiladigan kiberjinoyat","Xodim tomonidan sodir etilgan jinoyat","Dasturiy xato","Tizim nosozligi"],0),
("O'zbekiston Respublikasining 'Kiberxavfsizlik to'g'risida'gi qonuni qachon qabul qilingan?",["2022-yilda","2018-yilda","2025-yilda","2015-yilda"],0),
("Kiberetika nimani o'rganadi?",["Axborot texnologiyalari sohasidagi axloqiy me'yorlar va qoidalarni","Faqat dasturlash tillarini","Kompyuter qurilmalarini ta'mirlashni","Tarmoq tezligini oshirishni"],0),
("Raqamli kriminalistika (digital forensics) nima?",["Elektron qurilmalardan sud ekspertizasi uchun raqamli dalillarni yig'ish va tahlil qilish","Kompyuter viruslarini yaratish","Tarmoq sozlash","Dastur yozish"],0),
("Mobil kriminalistika qaysi qurilmalar bilan ishlaydi?",["Smartfonlar, planshetlar va boshqa mobil qurilmalar","Faqat shaxsiy kompyuterlar","Faqat serverlar","Faqat tarmoq uskunalari"],0),
("Xalqaro kiberqonunlarning asosiy maqsadi nima?",["Davlatlar o'rtasida kiberxavfsizlik sohasida hamkorlik va jinoyatlarga qarshi kurashish","Faqat bitta davlatning manfaatlarini himoyalash","Internet tezligini oshirish","Dasturiy ta'minotni yaratish"],0),
("Kiberjinoyatchilikka misol bo'ladigan harakatlar qaysi?",["Ma'lumotlarni o'g'irlash, tizimga ruxsatsiz kirish, firibgarlik","Yangi dastur yaratish","Kompyuter sotib olish","Internet brauzerdan foydalanish"],0),
("Fishing (phishing) hujumi qaysi jinoyat turiga kiradi?",["Ijtimoiy injineriya orqali amalga oshiriladigan kiberjinoyat","Fizik hujum","Dasturiy xato","Apparat nosozligi"],0),
("Kiberjinoyatchilikda DDoS hujumining maqsadi nima?",["Xizmatdan voz kechishga undash orqali tizimni ishdan chiqarish","Ma'lumotlarni shifrlash","Parolni o'zgartirish","Tarmoq tezligini oshirish"],0),
("Budapesht konvensiyasi nima haqida?",["Kiberjinoyatchilikning xalqaro miqyosda huquqiy jihatdan tartibga solinishi","Internet tezligini oshirish","Yangi dasturlash tilini yaratish","Ma'lumotlar bazasi standartlari"],0),
("Shaxsiy ma'lumotlarni ruxsatsiz to'plash qaysi soha buzilishiga tegishli?",["Konfidensiallik (maxfiylik) buzilishi","Yaxlitlik buzilishi","Foydalanuvchanlik buzilishi","Autentifikatsiya buzilishi"],0),
("Kiberxavfsizlik arxitekturasi nima?",["Tashkilotning axborot xavfsizligini ta'minlash uchun tuzilgan tizimli himoya strukturasi","Bino loyihasi","Tarmoq kabeli sxemasi","Kompyuter qurilmalarining ro'yxati"],0),
("Kiberxavfsizlik strategiyasi nimani belgilaydi?",["Tashkilotning uzoq muddatli xavfsizlik maqsadlari va ularga erishish yo'llarini","Faqat parol siyosatini","Faqat tarmoq sozlamalarini","Faqat virusga qarshi dasturni"],0),
("Xavfsizlik siyosatining zaruriyati nimada?",["Tashkilotda axborot xavfsizligini tartibga solish va boshqarish uchun","Faqat hujjat tayyorlash uchun","Internet tezligini oshirish uchun","Dasturiy ta'minotni yangilash uchun"],0),
("Xavfsizlik siyosatining iyerarxiyasi qanday tuzilgan?",["Korporativ siyosat, funksional siyosat, standartlar, protseduralar","Faqat bitta hujjatdan iborat","Faqat texnik ko'rsatmalar","Faqat yuridik hujjatlar"],0),
("Axborot xavfsizligi siyosatining turlari qaysilar?",["Dastur sathidagi, mavzu sathidagi va tizim sathidagi siyosatlar","Faqat tarmoq siyosati","Faqat parol siyosati","Faqat fizik xavfsizlik siyosati"],0),
("Xavfsizlik siyosatining afzalliklaridan biri:",["Xodimlarning xavfsizlik bo'yicha mas'uliyatini aniq belgilash","Tarmoq tezligini oshirish","Kompyuter narxini kamaytirish","Dasturiy ta'minotni bepul qilish"],0),
("Kiberxavfsizlik arxitekturasida 'chuqurlikda himoya' (defense in depth) tamoyili nimani anglatadi?",["Bir necha qatlamli himoya tizimini qurish","Faqat bitta kuchli himoya vositasidan foydalanish","Faqat tarmoqni himoyalash","Faqat parollarni kuchaytirish"],0),
("Xavfsizlik siyosati kim tomonidan tasdiqlanishi kerak?",["Tashkilot rahbariyati tomonidan","Faqat IT bo'limi tomonidan","Faqat oddiy xodimlar tomonidan","Faqat tashqi auditorlar tomonidan"],0),
("Xavfsizlik siyosati qanchalik tez-tez yangilanishi kerak?",["Muntazam ravishda va muhim o'zgarishlar sodir bo'lganda","Hech qachon o'zgartirilmasligi kerak","Faqat har 10 yilda bir marta","Faqat kiberhujum sodir bo'lgandan keyin"],0),
("Zero Trust (Nol ishonch) arxitekturasi nimani talab qiladi?",["Har bir foydalanuvchi va qurilmani har doim tekshirishni","Barcha foydalanuvchilarga to'liq ishonishni","Faqat ichki tarmoqdagi foydalanuvchilarga ishonishni","Faqat administratorlarga ishonishni"],0),
("Axborot xavfsizligi siyosatida 'minimal imtiyoz' tamoyili nimani anglatadi?",["Foydalanuvchilarga faqat ishlari uchun zarur bo'lgan minimal huquqlarni berish","Barcha foydalanuvchilarga administrator huquqlarini berish","Faqat bitta foydalanuvchiga barcha huquqlarni berish","Hech kimga hech qanday huquq bermaslik"],0),
("Xavfsizlik siyosatining xususiyatlaridan biri:",["Aniq, tushunarli va amaliy bo'lishi kerak","Faqat texnik tilda yozilishi kerak","Maxfiy bo'lishi va hech kim bilmasligi kerak","Juda uzun va murakkab bo'lishi kerak"],0),
("Kriptografiya nimani o'rganadi?",["Ma'lumotlarni shifrlash va himoyalash usullarini","Kompyuter qurilmalarini yig'ishni","Tarmoq kabellarini o'rnatishni","Operatsion tizimlarni yaratishni"],0),
("Kriptotizim nima?",["Shifrlash va deshifrlash algoritmlari, kalitlar va protokollar majmuasi","Faqat parol","Tarmoq uskunasi","Ma'lumotlar bazasi"],0),
("Kerkxofs prinsipi nimani bildiradi?",["Kriptotizimning xavfsizligi algoritmning maxfiyligiga emas, kalitning maxfiyligiga asoslanishi kerak","Algoritm doimo maxfiy bo'lishi kerak","Kalit ochiq bo'lishi kerak","Shifrlash kerak emas"],0),
("Ochiq matn (plaintext) nima?",["Shifrlanmagan, o'qilishi mumkin bo'lgan asl ma'lumot","Shifrlangan ma'lumot","Kalit","Xesh qiymat"],0),
("Shifrlangan matn (ciphertext) nima?",["Kriptografik algoritm yordamida o'zgartirilgan, o'qib bo'lmaydigan ma'lumot","Oddiy matn","Parol","Raqamli imzo"],0),
("Bir martalik bloknot (One-time pad) ning xususiyati:",["Nazariy jihatdan buzilishi mumkin bo'lmagan shifrlash usuli","Eng oddiy shifrlash usuli","Faqat raqamlarni shifrlaydi","Kalit kerak emas"],0),
("Kriptografiyaning qaysi bo'limi shifrlash bilan shug'ullanadi?",["Kriptografiya (shifrlash fani)","Kriptoanaliz","Steganografiya","Kriptologiya"],0),
("Kriptoanaliz nima?",["Shifrlangan ma'lumotlarni kalitsiz ochishga urinish fani","Ma'lumotlarni shifrlash usuli","Tarmoq himoyasi","Parol yaratish"],0),
("Sezar shifri qaysi shifrlash turiga kiradi?",["Almashtirishga asoslangan klassik shifr","Zamonaviy blokli shifr","Ochiq kalitli shifrlash","Xesh funksiya"],0),
("Steganografiya nimani o'rganadi?",["Ma'lumotlarni boshqa ma'lumotlar ichiga yashirishni","Ma'lumotlarni shifrlashni","Ma'lumotlarni o'chirishni","Ma'lumotlarni zaxiralashni"],0),
("Diffuziya (diffusion) kriptografiyada nimani anglatadi?",["Ochiq matndagi bitta bit o'zgarishi shifrlangan matnga maksimal ta'sir qilishi","Kalitning uzun bo'lishi","Algoritmning tez ishlashi","Ma'lumotning o'chirilishi"],0),
("Konfuziya (confusion) kriptografiyada nimani anglatadi?",["Kalit va shifrlangan matn o'rtasidagi bog'lanishni murakkablashtirish","Ma'lumotni siqish","Tarmoqni himoyalash","Parolni uzaytirish"],0),
("Kriptografik akslantirishlar nima?",["Ma'lumotlarni bir ko'rinishdan boshqa ko'rinishga o'zgartiruvchi matematik funksiyalar","Kompyuter monitori","Tarmoq kabeli","Printer"],0),
("Simmetrik shifrlash algoritmining asosiy xususiyati nima?",["Shifrlash va deshifrlash uchun bitta kalit ishlatiladi","Ikki xil kalit ishlatiladi","Kalit umuman ishlatilmaydi","Faqat ochiq kalit ishlatiladi"],0),
("AES (Advanced Encryption Standard) algoritmi qaysi toifaga kiradi?",["Simmetrik blokli shifrlash algoritmi","Ochiq kalitli algoritm","Xesh funksiya","Raqamli imzo algoritmi"],0),
("DES (Data Encryption Standard) algoritmi necha bitli kalit ishlatadi?",["56 bitli","128 bitli","256 bitli","512 bitli"],0),
("Oqimli (stream) shifrlash algoritmi qanday ishlaydi?",["Ma'lumotlarni bit yoki bayt bo'yicha ketma-ket shifrlaydi","Ma'lumotlarni qat'iy bloklarga bo'lib shifrlaydi","Ma'lumotlarni faqat bir yo'nalishda shifrlaydi","Ma'lumotlarni faqat siqadi"],0),
("Blokli (block) shifrlash algoritmi qanday ishlaydi?",["Ma'lumotlarni belgilangan uzunlikdagi bloklarga bo'lib shifrlaydi","Ma'lumotlarni bit bo'yicha ketma-ket shifrlaydi","Ma'lumotlarni faqat o'chiradi","Ma'lumotlarni faqat siqadi"],0),
("A5/1 algoritmi qayerda ishlatiladi?",["GSM mobil aloqa tizimida","Internet brauzerda","Elektron pochtada","Ma'lumotlar bazasida"],0),
("Simmetrik kriptotizimlardagi asosiy muammo nima?",["Kalitni xavfsiz almashish muammosi","Algoritmning juda tez ishlashi","Kalitning juda qisqa bo'lishi","Shifrlash imkonsizligi"],0),
("AES algoritmi necha bitli blok uzunligidan foydalanadi?",["128 bit","64 bit","256 bit","512 bit"],0),
("3DES algoritmi DESdan qanday farq qiladi?",["DES algoritmini uch marta qo'llaydi va xavfsizlikni oshiradi","Faqat bir marta shifrlaydi","Ochiq kalit ishlatadi","Kalit ishlatmaydi"],0),
("Simmetrik kriptotizimlarda kalit uzunligi xavfsizlikka qanday ta'sir qiladi?",["Kalit uzunroq bo'lsa, kuch bilan buzish qiyinlashadi","Kalit uzunligi xavfsizlikka ta'sir qilmaydi","Qisqa kalit xavfsizroq","Faqat 8 bitli kalit yetarli"],0),
("Simmetrik shifrlashning afzalligi:",["Tezkor ishlashi va kam resurs talab qilishi","Kalit almashish muammosi yo'qligi","Raqamli imzo yarata olishi","Ochiq kalit ishlatishi"],0),
("RC4 algoritmi qaysi toifaga kiradi?",["Oqimli simmetrik shifrlash algoritmi","Blokli shifrlash algoritmi","Xesh funksiya","Ochiq kalitli algoritm"],0),
("Ochiq kalitli kriptotizimda nechta kalit ishlatiladi?",["Ikkita: ochiq kalit va maxfiy kalit","Bitta kalit","Uchta kalit","Kalit ishlatilmaydi"],0),
("RSA algoritmi qaysi matematik muammoga asoslangan?",["Katta sonlarni ko'paytuvchilarga ajratish (faktorlash) muammosiga","Logarifm muammosiga","Chiziqli tenglamalar tizimiga","Geometrik hisoblashga"],0),
("Ochiq kalit (public key) kimga ma'lum bo'lishi kerak?",["Hamma uchun ochiq bo'lishi mumkin","Faqat jo'natuvchiga","Faqat qabul qiluvchiga","Hech kimga"],0),
("Maxfiy kalit (private key) kimda saqlanishi kerak?",["Faqat kalit egasida","Hamma uchun ochiq","Faqat serverda","Faqat jo'natuvchida"],0),
("Bir tomonlama funksiya (one-way function) nima?",["Hisoblash oson, lekin teskari hisoblash juda qiyin bo'lgan funksiya","Ikki tomonlama hisoblash mumkin bo'lgan funksiya","Faqat shifrlash uchun ishlatiladigan funksiya","Kalit yaratish funksiyasi"],0),
("Modul arifmetikasi (modular arithmetic) qanday ishlaydi?",["Sonlarni ma'lum songa bo'lgandagi qoldiq bilan ishlaydi","Oddiy qo'shish va ayirish","Faqat ko'paytirish","Faqat bo'lish"],0),
("RSA algoritmida xabarni shifrlash uchun qaysi kalit ishlatiladi?",["Qabul qiluvchining ochiq kaliti","Jo'natuvchining maxfiy kaliti","Umumiy parol","Xesh qiymat"],0),
("RSA algoritmida xabarni deshifrlash uchun qaysi kalit ishlatiladi?",["Qabul qiluvchining maxfiy kaliti","Jo'natuvchining ochiq kaliti","Umumiy parol","Sertifikat"],0),
("Ochiq kalitli kriptotizimlarning afzalligi:",["Kalitni xavfsiz almashish muammosini hal qilishi","Simmetrik algoritmlardan tezroq ishlashi","Kam xotira talab qilishi","Oddiy matematik asosga ega bo'lishi"],0),
("Ochiq kalitli kriptotizimlarning kamchiligi:",["Simmetrik algoritmlarga nisbatan sekinroq ishlashi","Kalit almashish muammosi mavjudligi","Kalitni boshqarish qiyinligi","Raqamli imzo yarata olmasligi"],0),
("Diffie-Hellman algoritmi nima uchun ishlatiladi?",["Ikki tomon o'rtasida xavfsiz kalit almashish uchun","Ma'lumotlarni shifrlash uchun","Raqamli imzo yaratish uchun","Xesh qiymat hisoblash uchun"],0),
("Ochiq kalitli kriptotizimlarda kalit uzunligi odatda qancha?",["1024, 2048 yoki 4096 bit","8 yoki 16 bit","56 yoki 64 bit","128 yoki 256 bit"],0),
("Xesh funksiya nima?",["Ixtiyoriy uzunlikdagi ma'lumotni qat'iy uzunlikdagi qiymatga aylantiradigan funksiya","Shifrlash algoritmi","Kalit almashish protokoli","Tarmoq protokoli"],0),
("Xesh funksiyaning asosiy xususiyati:",["Bir tomonlamalik - xesh qiymatdan asl ma'lumotni qayta tiklab bo'lmaydi","Ikki tomonlama ishlaydi","Kalit talab qiladi","Faqat matnlarni o'zgartiradi"],0),
("MD5 xesh algoritmi necha bitli xesh qiymat hosil qiladi?",["128 bit","256 bit","512 bit","64 bit"],0),
("SHA-256 xesh algoritmi necha bitli xesh qiymat hosil qiladi?",["256 bit","128 bit","64 bit","512 bit"],0),
("MAC (Message Authentication Code) nima?",["Xabarlarni autentifikatsiyalash kodi - xabar yaxlitligini va manbani tasdiqlaydi","Media Access Control manzili","Tarmoq protokoli","Shifrlash algoritmi"],0),
("Elektron raqamli imzo (ERI) nima uchun ishlatiladi?",["Xabar muallifini tasdiqlash va xabar yaxlitligini kafolatlash uchun","Faqat xabarni shifrlash uchun","Tarmoq tezligini oshirish uchun","Parolni saqlash uchun"],0),
("Raqamli imzo yaratishda qaysi kalit ishlatiladi?",["Imzolovchining maxfiy kaliti","Imzolovchining ochiq kaliti","Umumiy kalit","Sertifikat kaliti"],0),
("Raqamli imzoni tekshirishda qaysi kalit ishlatiladi?",["Imzolovchining ochiq kaliti","Imzolovchining maxfiy kaliti","Shaxsiy parol","Umumiy kalit"],0),
("Ochiq kalitlar infrastrukturasi (PKI) nima?",["Raqamli sertifikatlarni boshqarish uchun zarur bo'lgan texnologiya va siyosatlar to'plami","Tarmoq kabellari tizimi","Operatsion tizim","Ma'lumotlar bazasi"],0),
("X.509 raqamli sertifikat formati nimani o'z ichiga oladi?",["Sertifikat egasining ochiq kaliti, egasi haqida ma'lumot va sertifikat beruvchining imzosi","Faqat parol","Faqat IP manzil","Faqat foydalanuvchi nomi"],0),
("Sertifikatlashtirish markazi (CA) ning vazifasi nima?",["Raqamli sertifikatlarni berish va ularning haqiqiyligini tasdiqlash","Tarmoq tezligini boshqarish","Ma'lumotlarni shifrlash","Viruslarni aniqlash"],0),
("Xesh kolliziyasi nima?",["Ikki xil ma'lumot uchun bir xil xesh qiymat hosil bo'lishi","Xesh qiymatning yo'qolishi","Kalitning buzilishi","Tarmoq xatosi"],0),
("SSL/TLS protokoli nima uchun ishlatiladi?",["Internet orqali xavfsiz ma'lumot almashishni ta'minlash uchun","Faqat elektron pochta uchun","Faqat fayllarni siqish uchun","Faqat printer bilan bog'lanish uchun"],0),
("HTTPS protokolida qaysi xavfsizlik texnologiyasi ishlatiladi?",["SSL/TLS","Faqat parol","Faqat tarmoqlararo ekran","Faqat antivirus"],0),
("SSH (Secure Shell) nima uchun ishlatiladi?",["Masofaviy kompyuterlarga xavfsiz ulanish va boshqarish uchun","Faqat fayllarni o'chirish uchun","Faqat printer ulash uchun","Faqat video ko'rish uchun"],0),
("IPSec protokoli qaysi sathda ishlaydi?",["Tarmoq sathida (IP sathida)","Ilova sathida","Fizik sathda","Ma'lumotlar kanali sathida"],0),
("Apparat shifrlash va dasturiy shifrlash o'rtasidagi farq:",["Apparat shifrlash maxsus qurilma orqali, dasturiy shifrlash dastur orqali amalga oshiriladi","Farq yo'q","Apparat shifrlash sekinroq","Dasturiy shifrlash xavfsizroq"],0),
("Disk sathida shifrlash nimani himoyalaydi?",["Butun disk yoki bo'limning ma'lumotlarini ruxsatsiz kirishdan","Faqat bitta faylni","Faqat tarmoq trafikini","Faqat elektron pochtani"],0),
("Blokchain texnologiyasining asosiy xususiyati:",["Markazlashtirilmagan va o'zgartirib bo'lmaydigan ma'lumotlar zanjiri","Markazlashtirilgan ma'lumotlar bazasi","Faqat kriptovalyuta uchun","Oddiy ro'yxat"],0),
("PGP (Pretty Good Privacy) nima uchun ishlatiladi?",["Elektron pochta xabarlarini shifrlash va raqamli imzolash uchun","Tarmoq tezligini oshirish uchun","Viruslarni aniqlash uchun","Operatsion tizimni o'rnatish uchun"],0),
("E-hukumat tizimlarida kriptografiyaning roli:",["Davlat xizmatlarini xavfsiz ko'rsatish va fuqarolar ma'lumotlarini himoyalash","Faqat veb-saytlarni bezash","Internet tezligini oshirish","Kompyuterlar sonini ko'paytirish"],0),
("Fayl tizim sathida shifrlash nimani anglatadi?",["Alohida fayllar yoki papkalarni shifrlash","Butun diskni shifrlash","Tarmoq trafikini shifrlash","Elektron pochtani shifrlash"],0),
("Elektron to'lov tizimlarida kriptografiya qanday qo'llaniladi?",["Tranzaksiyalarni shifrlash va autentifikatsiyalash orqali","Faqat kvitansiya chop etish orqali","Faqat kassani boshqarish orqali","Faqat tovarlar ro'yxatini ko'rish orqali"],0),
("VPN (Virtual Private Network) da qaysi kriptografik protokol keng ishlatiladi?",["IPSec va SSL/TLS","Faqat HTTP","Faqat FTP","Faqat SMTP"],0),
("Identifikatsiya nima?",["Foydalanuvchining o'zini tizimga tanitishi (login, ID)","Foydalanuvchi huquqlarini belgilash","Parolni tekshirish","Tarmoqqa ulanish"],0),
("Autentifikatsiya nima?",["Foydalanuvchi haqiqatan ham u ekanligini tasdiqlash jarayoni","Foydalanuvchiga huquq berish","Foydalanuvchini tizimda ro'yxatdan o'tkazish","Foydalanuvchini tizimdan chiqarish"],0),
("Avtorizatsiya nima?",["Tasdiqlangan foydalanuvchiga resurslardan foydalanish huquqlarini belgilash","Foydalanuvchini aniqlash","Parolni tekshirish","Tizimga kirish"],0),
("Bir tomonlama autentifikatsiya nima?",["Faqat bir tomon (odatda foydalanuvchi) o'zini tasdiqlashi","Ikki tomon ham bir-birini tasdiqlashi","Autentifikatsiyasiz kirish","Faqat parol kiritish"],0),
("Ikki tomonlama autentifikatsiya nima?",["Ikkala tomon ham bir-birini o'zaro tasdiqlashi","Faqat server foydalanuvchini tekshirishi","Ikki marta parol kiritish","Ikki xil login ishlatish"],0),
("Ko'p omilli autentifikatsiya (MFA) nima?",["Ikki yoki undan ortiq autentifikatsiya usulini birgalikda qo'llash","Faqat bitta parol ishlatish","Bir necha marta login kiritish","Ko'p foydalanuvchi bir vaqtda kirishi"],0),
("Autentifikatsiya omillaridan biri - 'Bilish' (knowledge) ga misol:",["Parol, PIN-kod, maxfiy savol","Barmoq izi","Smart-karta","Yuz tasviri"],0),
("Autentifikatsiya omillaridan biri - 'Ega bo'lish' (possession) ga misol:",["Smart-karta, token, mobil telefon","Parol","PIN-kod","Maxfiy savol javobi"],0),
("Autentifikatsiya omillaridan biri - 'Bo'lish' (inherence) ga misol:",["Barmoq izi, yuz tasviri, ko'z qorachig'i","Parol","Smart-karta","PIN-kod"],0),
("Biometrik autentifikatsiya tizimi nimaga asoslangan?",["Insonning noyob jismoniy yoki xulq-atvor xususiyatlariga","Faqat parollarga","Faqat smart-kartalarga","Faqat PIN-kodlarga"],0),
("Parol tizimlarining asosiy kamchiligi:",["Parollar o'g'irlanishi, taxmin qilinishi yoki unutilishi mumkin","Parollar juda xavfsiz","Parollar hech qachon buzilmaydi","Parollar biometrikadan xavfsizroq"],0),
("OTP (One-Time Password) nima?",["Faqat bir marta ishlatiladigan vaqtinchalik parol","Doimiy parol","Administrator paroli","Tarmoq paroli"],0),
("Biometrik tizimlarning afzalligi:",["Unutilishi yoki o'g'irlanishi mumkin bo'lmagan noyob identifikator","Arzon narxi","Oddiy o'rnatilishi","Kalit kerak emasligi"],0),
("Foydalanishni boshqarish (Access Control) nima?",["Resurslardan foydalanish huquqlarini belgilash va nazorat qilish jarayoni","Tarmoq tezligini boshqarish","Kompyuter haroratini nazorat qilish","Dasturlarni o'rnatish"],0),
("DAC (Discretionary Access Control) usulining xususiyati:",["Resurs egasi boshqa foydalanuvchilarga huquqlarni o'zi belgilaydi","Faqat administrator huquq beradi","Rollar asosida huquq beriladi","Atributlar asosida huquq beriladi"],0),
("MAC (Mandatory Access Control) usulining xususiyati:",["Foydalanish huquqlari markaziy siyosat asosida tizim tomonidan boshqariladi","Resurs egasi huquqlarni belgilaydi","Foydalanuvchi o'zi huquqlarini o'zgartiradi","Hech qanday cheklov yo'q"],0),
("RBAC (Role-Based Access Control) usulining xususiyati:",["Foydalanuvchilarga rollar orqali huquqlar beriladi","Har bir foydalanuvchiga alohida huquq beriladi","Faqat administrator foydalana oladi","Cheklov yo'q"],0),
("ABAC (Attribute-Based Access Control) usulining xususiyati:",["Foydalanuvchi, resurs va muhit atributlari asosida huquqlar belgilanadi","Faqat rollar asosida","Faqat parol asosida","Faqat vaqt asosida"],0),
("Foydalanishni boshqarish matritsasi nima?",["Foydalanuvchilar va resurslar o'rtasidagi huquqlarni ko'rsatuvchi jadval","Shifrlash algoritmi","Tarmoq diagrammasi","Ma'lumotlar bazasi"],0),
("ACL (Access Control List) nima?",["Resursga kim qanday huquqlarga ega ekanligini ko'rsatadigan ro'yxat","Foydalanuvchilar ro'yxati","Kompyuterlar ro'yxati","Dasturlar ro'yxati"],0),
("C-list (Capability List) nima?",["Foydalanuvchi qaysi resurslarga qanday huquqlarga ega ekanligini ko'rsatadigan ro'yxat","Kompyuterlar ro'yxati","Tarmoq uskunalari ro'yxati","Dasturlar ro'yxati"],0),
("RBAC usulida 'rol' nima?",["Tashkilotdagi lavozim yoki funksiyaga mos keladigan huquqlar to'plami","Foydalanuvchi nomi","Parol turi","IP manzil"],0),
("MAC usulida xavfsizlik tamoyili (label) nima?",["Har bir resurs va foydalanuvchiga beriladigan maxfiylik darajasi","Kompyuter nomi","Tarmoq manzili","Dastur versiyasi"],0),
("DAC usulining kamchiligi nima?",["Resurs egasi noto'g'ri huquqlar berib, xavfsizlikni buzishi mumkin","Juda qat'iy nazorat","Juda sekin ishlashi","Rollarni qo'llab-quvvatlamasligi"],0),
("Foydalanishni boshqarishda 'ruxsat berish' va 'rad etish' tamoyillari qanday ishlaydi?",["Agar aniq ruxsat berilmagan bo'lsa, sukut bo'yicha rad etiladi","Agar rad etilmagan bo'lsa, ruxsat beriladi","Hamma narsaga ruxsat beriladi","Hamma narsa rad etiladi"],0),
("Bell-LaPadula modeli nimani himoyalaydi?",["Ma'lumotlarning konfidensialligini (maxfiyligini)","Ma'lumotlarning yaxlitligini","Ma'lumotlarning foydalanuvchanligini","Tarmoq tezligini"],0),
("Bell-LaPadula modelining 'yuqoriga o'qimaslik' (no read up) qoidasi nimani anglatadi?",["Past maxfiylik darajasidagi foydalanuvchi yuqori darajadagi ma'lumotni o'qiy olmaydi","Yuqori darajadagi foydalanuvchi past darajaga yoza olmaydi","Hamma barcha ma'lumotlarni o'qiy oladi","Hech kim hech narsani o'qiy olmaydi"],0),
("Bell-LaPadula modelining 'pastga yozmaslik' (no write down) qoidasi nimani anglatadi?",["Yuqori maxfiylik darajasidagi foydalanuvchi past darajaga ma'lumot yoza olmaydi","Past darajadagi foydalanuvchi yuqoriga yoza olmaydi","Hamma hamma joyga yoza oladi","Hech kim yoza olmaydi"],0),
("Biba modeli nimani himoyalaydi?",["Ma'lumotlarning yaxlitligini (butunligini)","Ma'lumotlarning maxfiyligini","Ma'lumotlarning foydalanuvchanligini","Tarmoq xavfsizligini"],0),
("Biba modelining 'pastdan o'qimaslik' (no read down) qoidasi nimani anglatadi?",["Yuqori yaxlitlik darajasidagi foydalanuvchi past darajadagi ma'lumotni o'qimasligi kerak","Past darajadagi foydalanuvchi yuqoriga o'qiy olmaydi","Hamma barcha ma'lumotlarni o'qiy oladi","Faqat administrator o'qiy oladi"],0),
("Biba modelining 'yuqoriga yozmaslik' (no write up) qoidasi nimani anglatadi?",["Past yaxlitlik darajasidagi foydalanuvchi yuqori darajaga yoza olmaydi","Yuqori darajadagi foydalanuvchi pastga yoza olmaydi","Hamma hamma joyga yoza oladi","Faqat administrator yoza oladi"],0),
("Bell-LaPadula va Biba modellari o'rtasidagi asosiy farq:",["Bell-LaPadula maxfiylikni, Biba esa yaxlitlikni himoyalaydi","Ikkisi ham bir xil narsani himoyalaydi","Bell-LaPadula tezroq ishlaydi","Biba yangi model"],0),
("Ko'p sathli xavfsizlik (MLS) modeli nimani nazarda tutadi?",["Turli maxfiylik darajalaridagi ma'lumotlarni bitta tizimda boshqarish","Faqat bitta darajadagi xavfsizlik","Faqat fizik xavfsizlik","Tarmoq tezligini boshqarish"],0),
("Mantiqiy foydalanishni boshqarish nimani anglatadi?",["Dasturiy va texnik vositalar orqali ma'lumotlarga kirishni cheklash","Eshik va qulflar orqali himoyalash","Kuzatuv kameralari o'rnatish","Qo'riqchi qo'yish"],0),
("Fizik foydalanishni boshqarish nimani anglatadi?",["Jismoniy vositalar orqali ma'lumotlar joylashgan hududga kirishni cheklash","Parollar orqali himoyalash","Shifrlash orqali himoyalash","Tarmoqlararo ekran orqali himoyalash"],0),
("Clark-Wilson modeli nimani ta'minlaydi?",["Ma'lumotlar yaxlitligini tranzaksiyalar orqali boshqarish","Faqat maxfiylikni","Faqat foydalanuvchanlikni","Faqat tarmoq xavfsizligini"],0),
("Chinese Wall modeli nimani himoyalaydi?",["Manfaatlar to'qnashuvini oldini olish","Faqat ma'lumotlar maxfiyligini","Faqat fizik xavfsizlikni","Faqat tarmoq xavfsizligini"],0),
("Fizik xavfsizlikning zaruriyati nimada?",["Axborot saqlanadigan jismoniy muhitni tabiiy va sun'iy tahdidlardan himoyalash","Faqat dasturiy ta'minotni himoyalash","Faqat tarmoq tezligini oshirish","Faqat elektr energiyasini tejash"],0),
("Tabiiy tahdidlarga nimalar kiradi?",["Zilzila, suv toshqini, yong'in, momaqaldiroq","Xakerlik hujumlari","Virus tarqalishi","Parol o'g'irlash"],0),
("Sun'iy tahdidlarga nimalar kiradi?",["O'g'irlik, qasddan buzish, diversiya, sabotaj","Zilzila","Suv toshqini","Yong'in"],0),
("Fizik xavfsizlikni nazoratlash usullaridan biri:",["Kuzatuv kameralari va kirishni nazorat qilish tizimlari","Shifrlash algoritmlari","Virusga qarshi dasturlar","Tarmoqlararo ekranlar"],0),
("Ma'lumotlarni xavfsiz yo'q qilish usullari qaysilar?",["Qog'oz hujjatlarni maydalash, elektron axborot tashuvchilarni degaussing yoki fizik buzish","Faqat o'chirib tashlash","Savatga tashlash","Faylni qayta nomlash"],0),
("Degaussing nima?",["Kuchli magnit maydoni orqali ma'lumot tashuvchidagi ma'lumotlarni yo'q qilish","Ma'lumotlarni shifrlash","Ma'lumotlarni siqish","Ma'lumotlarni ko'chirish"],0),
("Server xonasida harorat nazorati nima uchun muhim?",["Uskunalarning haddan tashqari qizib ketishini oldini olish uchun","Faqat xodimlar qulayligi uchun","Faqat energiya tejash uchun","Faqat chiroyli ko'rinish uchun"],0),
("UPS (Uzluksiz quvvat manbai) ning vazifasi:",["Elektr uzilganda uskunalarni vaqtincha quvvat bilan ta'minlash","Tarmoq tezligini oshirish","Ma'lumotlarni shifrlash","Viruslarni aniqlash"],0),
("Biometrik kirishni nazorat qilish tizimlariga misol:",["Barmoq izi skaneri, yuz tanish tizimi, ko'z pardasi skaneri","Parol kiritish","Kalit bilan eshik ochish","Telefon orqali qo'ng'iroq qilish"],0),
("Ogohlik va o'qitish fizik xavfsizlikda qanday ahamiyatga ega?",["Xodimlarni xavfsizlik qoidalari va tahdidlar haqida xabardor qilish orqali himoyani kuchaytiradi","Hech qanday ahamiyati yo'q","Faqat texnik xodimlar uchun kerak","Faqat rahbarlar uchun kerak"],0),
("Ma'lumotlarni saqlash xonasiga kirish qanday nazorat qilinishi kerak?",["Faqat ruxsat etilgan shaxslar kirishi va barcha kirishlar qayd qilinishi kerak","Hamma kiravera olishi kerak","Faqat tunda nazorat qilinishi kerak","Nazorat kerak emas"],0),
("Yong'inga qarshi himoya tizimlarining ahamiyati:",["Uskunalar va ma'lumotlarni yong'indan himoyalash va avtomatik o'chirish tizimini ta'minlash","Faqat bino ko'rinishini yaxshilash","Faqat qonun talabi","Ahamiyati yo'q"],0),
("LAN (Local Area Network) nima?",["Cheklangan hududdagi (bino, ofis) kompyuterlarni birlashtiruvchi tarmoq","Butun dunyo bo'ylab tarqalgan tarmoq","Faqat simsiz tarmoq","Faqat uyali aloqa tarmog'i"],0),
("WAN (Wide Area Network) nima?",["Katta geografik hududni qamrab oluvchi tarmoq","Faqat bitta bino ichidagi tarmoq","Faqat simsiz tarmoq","Faqat lokal tarmoq"],0),
("OSI modelida nechta qatlam bor?",["7 ta","4 ta","5 ta","3 ta"],0),
("TCP/IP modelida nechta qatlam bor?",["4 ta","7 ta","5 ta","3 ta"],0),
("Razvedka (reconnaissance) hujumi nima?",["Nishon tizim haqida ma'lumot to'plash maqsadidagi hujum","Tizimni buzish","Ma'lumotlarni o'chirish","Virusni tarqatish"],0),
("Kirish hujumi (access attack) nima?",["Ruxsatsiz tizim yoki ma'lumotlarga kirish uchun amalga oshiriladigan hujum","Ma'lumot to'plash","Tarmoq tezligini o'lchash","Tizimni yangilash"],0),
("DoS (Denial of Service) hujumi nimani maqsad qiladi?",["Tizim yoki xizmatni foydalanuvchilarga yaroqsiz holga keltirish","Ma'lumotlarni o'g'irlash","Parolni o'zgartirish","Tizimga kirish"],0),
("DDoS hujumi DoS dan qanday farq qiladi?",["Ko'plab kompyuterlardan bir vaqtda hujum qilinadi","Bitta kompyuterdan hujum qilinadi","Hujum amalga oshirilmaydi","Faqat ichki tarmoqda"],0),
("Man-in-the-Middle (MITM) hujumi nima?",["Hujumchi ikki tomon orasidagi aloqani tutib, ma'lumotlarni tinglash yoki o'zgartirish","Kompyuterni fizik buzish","Virusni tarqatish","Parolni o'zgartirish"],0),
("Ichki tahdid (insider threat) nima?",["Tashkilot xodimi yoki ishonchli shaxs tomonidan keltirilgan xavf","Tashqi haker tomonidan hujum","Virus tarqalishi","Tabiiy ofat"],0),
("Tarmoq topologiyalarining turlari qaysilar?",["Yulduz, halqa, shina, to'r (mesh), daraxt","Faqat yulduz","Faqat halqa","Faqat shina"],0),
("TCP protokolining xususiyati:",["Ishonchli ulanishga asoslangan ma'lumot uzatish protokoli","Ishonchsiz, ulanishsiz protokol","Faqat video uzatish uchun","Faqat pochta uchun"],0),
("Sniffing hujumi nima?",["Tarmoqdagi ma'lumot paketlarini ruxsatsiz tutib olish va tahlil qilish","Tarmoq kabelini uzish","Kompyuterni o'chirish","Parolni o'zgartirish"],0),
("Tarmoqlararo ekran (Firewall) nima?",["Tarmoq trafikini nazorat qilib, ruxsatsiz kirishlardan himoyalovchi vosita","Virusga qarshi dastur","Ma'lumotlar bazasi","Operatsion tizim"],0),
("VPN (Virtual Private Network) nima?",["Internet orqali xavfsiz shifrlangan virtual kanal yaratish texnologiyasi","Oddiy internet ulanishi","Wi-Fi tarmog'i","Lokal tarmoq"],0),
("IDS (Intrusion Detection System) nima?",["Suqilib kirishlarni aniqlash tizimi","Virusga qarshi dastur","Shifrlash algoritmi","Tarmoq kabeli"],0),
("IPS (Intrusion Prevention System) IDS dan qanday farq qiladi?",["IPS faqat aniqlamaydi, balki hujumni avtomatik bloklaydi ham","IPS faqat aniqlaydi","Farq yo'q","IPS sekinroq ishlaydi"],0),
("DLP (Data Leakage Prevention) tizimi nima?",["Ma'lumotlarning sirqib chiqishini (sizib ketishini) oldini olish tizimi","Virusga qarshi dastur","Tarmoq tezligini oshirish vositasi","Ma'lumotlar bazasi"],0),
("Honeypot (tuzoq) nima?",["Hujumchilarni jalb qilish va ularning usullarini o'rganish uchun maxsus qo'yilgan yolg'on nishon","Haqiqiy server","Ma'lumotlar bazasi","Shifrlash vositasi"],0),
("Paketli filtrlash tarmoqlararo ekranda qanday ishlaydi?",["Har bir tarmoq paketini IP manzili, port va protokol bo'yicha tekshiradi","Faqat foydalanuvchi nomini tekshiradi","Faqat parolni tekshiradi","Faqat fayllarni tekshiradi"],0),
("Stateful inspection (holatni kuzatuvchi) tarmoqlararo ekran nima?",["Ulanishlarning holatini kuzatib, kontekstga qarab trafikni filtrlaydi","Faqat paketlarni alohida tekshiradi","Faqat parolni tekshiradi","Faqat viruslarni aniqlaydi"],0),
("DMZ (Demilitarized Zone) nima?",["Ichki va tashqi tarmoq o'rtasidagi bufer zona","Maxfiy tarmoq","Simsiz tarmoq","Lokal tarmoq"],0),
("Proksi-server nima uchun ishlatiladi?",["Foydalanuvchi va internet o'rtasida vositachilik qilish va xavfsizlikni oshirish","Ma'lumotlarni shifrlash","Viruslarni yaratish","Tarmoq kabellarini ulash"],0),
("NIDS (Network-based IDS) nimani kuzatadi?",["Tarmoq trafikini tahlil qilib, shubhali faoliyatni aniqlaydi","Faqat bitta kompyuterdagi fayllarni","Faqat elektron pochtani","Faqat printer trafikini"],0),
("HIDS (Host-based IDS) nimani kuzatadi?",["Bitta kompyuter yoki serverdagi faoliyatni kuzatadi","Butun tarmoq trafikini","Faqat internet trafikini","Faqat simsiz trafikni"],0),
("Wi-Fi simsiz tarmog'ining asosiy xavfsizlik muammosi:",["Signal havo orqali tarqalgani uchun tinglash va ruxsatsiz ulanish oson","Kabel kerak bo'lishi","Juda sekin ishlashi","Faqat bir qurilma ulana olishi"],0),
("WEP (Wired Equivalent Privacy) protokolining kamchiligi:",["Zaif shifrlash kaliti tufayli oson buzilishi","Juda kuchli va sekin ishlashi","Faqat yangi qurilmalarda ishlashi","Hech qanday kamchiligi yo'q"],0),
("WPA (Wi-Fi Protected Access) WEP dan qanday ustunligi bor?",["Yanada kuchli shifrlash va dinamik kalit almashinuvi","Sekinroq ishlaydi","Kamroq xavfsiz","Faqat eski qurilmalarda ishlaydi"],0),
("WPA2 da qaysi shifrlash algoritmi ishlatiladi?",["AES (Advanced Encryption Standard)","DES","RC4","MD5"],0),
("Simsiz tarmoqlarga bo'ladigan 'Evil Twin' hujumi nima?",["Haqiqiy tarmoqqa o'xshash soxta nuqta yaratib, foydalanuvchilarni jalb qilish","Tarmoq kabelini uzish","Serverni o'chirish","Parolni o'zgartirish"],0),
("SSID (Service Set Identifier) nima?",["Simsiz tarmoqning nomi","Shifrlash kaliti","IP manzil","MAC manzil"],0),
("SSID yashirish (hiding) simsiz tarmoq xavfsizligini oshiradimi?",["To'liq himoya bermaydi, lekin tasodifiy ulanishlarni kamaytirishi mumkin","To'liq xavfsizlikni ta'minlaydi","Hech qanday foydasi yo'q","Tarmoq ishlamaydigan bo'lib qoladi"],0),
("MAC filtrlash simsiz tarmoqda qanday ishlaydi?",["Faqat ro'yxatga kiritilgan MAC manzilli qurilmalarga ulanishga ruxsat berish","Barcha qurilmalarga ruxsat berish","Tarmoq tezligini oshirish","Ma'lumotlarni shifrlash"],0),
("Simsiz tarmoqdagi 'War driving' nima?",["Ochiq yoki zaif himoyalangan simsiz tarmoqlarni qidirish uchun atrofda haydab yurish","Kompyuter o'yini","Tarmoq o'rnatish usuli","Server sozlash"],0),
("WPA3 protokolining WPA2 dan afzalliklari:",["Yanada kuchli shifrlash va ommaviy Wi-Fi tarmoqlarida individual shifrlash","WPA2 dan kamroq xavfsiz","Faqat eski qurilmalar uchun","Hech qanday farq yo'q"],0),
("Bluetooth xavfsizlik muammolaridan biri:",["Bluejacking va Bluesnarfing kabi hujumlarga zaiflik","Juda kuchli xavfsizlik","Hech qanday muammo yo'q","Faqat kompyuterlarda ishlashi"],0),
("Simsiz tarmoqda xavfsizlikni oshirish uchun eng muhim chora:",["Kuchli shifrlash (WPA2/WPA3) va murakkab parol ishlatish","Tarmoqni o'chirib qo'yish","Faqat bitta qurilma ulash","Hech narsa qilmaslik"],0),
("Bulutli hisoblash (Cloud Computing) nima?",["Internet orqali hisoblash resurslarini (server, saqlash, dasturlar) taqdim etish","Faqat ma'lumotlarni saqlash","Faqat elektron pochta xizmati","Lokal kompyuterda ishlash"],0),
("Bulutli hisoblash modellaridan biri - IaaS nima?",["Infratuzilma xizmati (Infrastructure as a Service)","Dastur xizmati","Platforma xizmati","Ma'lumot xizmati"],0),
("Bulutli hisoblash modellaridan biri - PaaS nima?",["Platforma xizmati (Platform as a Service)","Infratuzilma xizmati","Dastur xizmati","Xavfsizlik xizmati"],0),
("Bulutli hisoblash modellaridan biri - SaaS nima?",["Dastur xizmati (Software as a Service)","Infratuzilma xizmati","Platforma xizmati","Tarmoq xizmati"],0),
("Bulutli hisoblashda asosiy xavfsizlik muammosi:",["Ma'lumotlar uchinchi tomon serverlarida saqlanishi va nazorat yo'qolishi","Juda tez ishlashi","Juda arzon bo'lishi","Hech qanday muammo yo'q"],0),
("IoT (Internet of Things) nima?",["Jismoniy qurilmalarning internet orqali o'zaro bog'lanishi va ma'lumot almashishi","Faqat kompyuterlar tarmog'i","Faqat telefonlar tarmog'i","Faqat serverlar tarmog'i"],0),
("IoT qurilmalarining xavfsizlik muammolari nimada?",["Kam resursli qurilmalar, zaif parollar, yangilanishlar yo'qligi","Juda kuchli xavfsizlik","Hech qanday muammo yo'q","Faqat fizik xavflar"],0),
("IoT arxitekturasining asosiy qatlamlari:",["Idrok qatlami (sensorlar), tarmoq qatlami, ilova qatlami","Faqat bitta qatlam","Faqat tarmoq qatlami","Faqat ilova qatlami"],0),
("Bulutli hisoblashda ma'lumotlar maxfiyligi (privacy) muammosi nimada?",["Shaxsiy ma'lumotlar provayderlar tomonidan ko'rilishi yoki sizib ketishi mumkin","Ma'lumotlar juda xavfsiz","Hech qanday muammo yo'q","Faqat fizik xavf"],0),
("IoT qurilmalarida standart parollarni o'zgartirmaslik qanday xavf tug'diradi?",["Hujumchilar standart parollarni ishlatib qurilmaga osongina kira oladi","Hech qanday xavf yo'q","Qurilma tezroq ishlaydi","Parol o'zgartirish kerak emas"],0),
("Bulutli hisoblashda xavfsizlikni oshirish usullari:",["Ma'lumotlarni shifrlash, kuchli autentifikatsiya, doimiy monitoring","Hech narsa qilmaslik","Faqat parol ishlatish","Faqat antivirus o'rnatish"],0),
("IoT botnet nima?",["Viruslangan IoT qurilmalaridan tashkil topgan, hujumlar uchun ishlatiladigan tarmoq","Foydali IoT tarmog'i","IoT qurilmalar do'koni","IoT dasturlash tili"],0),
("'IoT' tushunchasi birinchi marta nechanchi yilda taklif etilgan?",["1999-yil","1990-yil","2005-yil","2010-yil"],0),
("Zaxira nusxalash (backup) nima uchun zarur?",["Ma'lumotlar yo'qolgan yoki buzilgan holda ularni qayta tiklash imkonini beradi","Tarmoq tezligini oshirish uchun","Viruslarni aniqlash uchun","Kompyuter tezligini oshirish uchun"],0),
("RAID texnologiyasi nima?",["Bir necha diskni birlashtirib ishonchlilik va tezlikni oshirish texnologiyasi","Virusga qarshi dastur","Shifrlash algoritmi","Tarmoq protokoli"],0),
("RAID 1 qanday ishlaydi?",["Ma'lumotlarni ikki diskda bir xil nusxalaydi (mirroring)","Ma'lumotlarni bir diskda saqlaydi","Ma'lumotlarni siqadi","Ma'lumotlarni shifrlaydi"],0),
("RAID 5 ning xususiyati:",["Ma'lumotlarni parchalab tarqatadi va paritet ma'lumoti orqali himoyalaydi","Faqat bitta diskda saqlaydi","Faqat ikkita diskda nusxalaydi","Ma'lumotlarni shifrlaydi"],0),
("To'liq zaxira nusxalash (full backup) nima?",["Barcha ma'lumotlarning to'liq nusxasini yaratish","Faqat o'zgargan fayllarni nusxalash","Faqat yangi fayllarni nusxalash","Ma'lumotlarni o'chirish"],0),
("Inkremental zaxira nusxalash nima?",["Faqat oxirgi zaxiradan keyin o'zgargan ma'lumotlarni nusxalash","Barcha ma'lumotlarni nusxalash","Faqat eski fayllarni nusxalash","Ma'lumotlarni o'chirish"],0),
("Differensial zaxira nusxalash nima?",["Oxirgi to'liq zaxiradan keyin o'zgargan barcha ma'lumotlarni nusxalash","Faqat oxirgi inkremental zaxiradan keyingi o'zgarishlar","Barcha ma'lumotlarni nusxalash","Ma'lumotlarni o'chirish"],0),
("Ma'lumotlarni yo'qolish sabablariga nimalar kiradi?",["Apparat nosozligi, dasturiy xatolar, inson xatolari, tabiiy ofatlar","Faqat viruslar","Faqat hakerlar","Faqat elektr uzilishi"],0),
("Ma'lumotlarni qayta tiklash (data recovery) nima?",["Yo'qolgan yoki buzilgan ma'lumotlarni maxsus vositalar yordamida tiklash","Ma'lumotlarni shifrlash","Ma'lumotlarni o'chirish","Ma'lumotlarni uzatish"],0),
("Hodisalarni qaydlash (logging) nima uchun muhim?",["Tizimda sodir bo'lgan voqealarni kuzatish va xavfsizlik hodisalarini tahlil qilish uchun","Faqat tarmoq tezligini o'lchash uchun","Faqat diskda joy bo'shatish uchun","Faqat foydalanuvchilarni hisoblash uchun"],0),
("Windows OT da hodisa (event) turlariga nimalar kiradi?",["Xato (Error), ogohlantirish (Warning), ma'lumot (Information), muvaffaqiyat auditi","Faqat xato","Faqat ogohlantirish","Faqat ma'lumot"],0),
("RPO (Recovery Point Objective) nima?",["Ma'lumotlar yo'qolishining maqbul maksimal vaqt oralig'i","Tiklash uchun sarflanadigan vaqt","Tarmoq tezligi","Disk hajmi"],0),
("Veb saytlardagi eng keng tarqalgan zaifliklardan biri:",["SQL inyeksiya","Tarmoq kabelining uzilishi","Kompyuter ekranining sinishi","Printerning ishdan chiqishi"],0),
("XSS (Cross-Site Scripting) hujumi nima?",["Veb sahifaga zararli skript kodini kiritish hujumi","Tarmoq kabelini uzish","Serverni fizik buzish","Parolni o'zgartirish"],0),
("SQL inyeksiya hujumi nima?",["Ma'lumotlar bazasiga zararli SQL buyruqlarini kiritish hujumi","Tarmoq trafigini tinglash","Virusni tarqatish","Fizik buzish"],0),
("Kuki (cookie) nima?",["Veb sayt tomonidan brauzerda saqlanadigan kichik ma'lumot fayli","Virus turi","Shifrlash kaliti","Tarmoq protokoli"],0),
("Xavfsiz dasturlash tillari (memory-safe) ga misol:",["Rust, Python, Java","C, Assembly","Faqat C++","Faqat Assembly"],0),
("OWASP Top 10 nima?",["Eng keng tarqalgan veb ilova zaifliklarining ro'yxati","Eng yaxshi 10 ta dasturlash tili","Eng tez 10 ta kompyuter","Eng yaxshi 10 ta antivirus"],0),
("Brauzerda shaxsiy ma'lumotlarni himoyalash usullari:",["HTTPS ishlatish, kukilarni boshqarish, shaxsiy rejimda ko'rish","Hech narsa qilmaslik","Faqat bitta saytdan foydalanish","Internetni o'chirish"],0),
("Mobil operatsion tizimlar xavfsizligi muammolari:",["Ruxsatsiz ilovalar, zaif ruxsatlar, ma'lumot sizib ketishi","Hech qanday muammo yo'q","Faqat batareya muammosi","Faqat ekran muammosi"],0),
("Linux OT ning xavfsizlik afzalligi:",["Ochiq kodli bo'lganligi uchun zaifliklar tezroq aniqlanadi va tuzatiladi","Viruslar ko'p tarqaladi","Hech qanday afzalligi yo'q","Faqat serverlar uchun"],0),
("Windows OT da foydalanuvchi hisobini nazorat qilish (UAC) nima?",["Dasturlar administrator huquqlari bilan ishlashdan oldin foydalanuvchidan ruxsat so'rash","Virusga qarshi dastur","Tarmoqlararo ekran","Shifrlash vositasi"],0),
("CSRF (Cross-Site Request Forgery) hujumi nima?",["Foydalanuvchi nomidan ruxsatsiz so'rovlarni yuborish hujumi","Tarmoqni buzish","Virusni yaratish","Parolni o'chirish"],0),
("Dasturiy ta'minotni yangilash (patch management) nima uchun muhim?",["Aniqlangan zaifliklarni bartaraf etish va xavfsizlikni oshirish uchun","Faqat yangi funksiyalar qo'shish uchun","Faqat dastur ko'rinishini o'zgartirish uchun","Hech qanday ahamiyati yo'q"],0),
("Zararli dastur (malware) nima?",["Kompyuter tizimiga zarar yetkazish uchun yaratilgan dasturiy ta'minot","Foydali dastur","Operatsion tizim","Tarmoq protokoli"],0),
("Kompyuter virusi nima?",["O'zini boshqa dasturlarga biriktiruvchi va tarqaluvchi zararli dastur","Foydali dastur","Operatsion tizim","Ma'lumotlar bazasi"],0),
("Troyan (trojan) dasturining xususiyati:",["Foydali dastur sifatida ko'rinib, aslida zararli funksiyalarni bajaradi","O'zini ko'paytiradi","Faqat tarmoq orqali tarqaladi","Foydali dastur"],0),
("Qurt (worm) virusdan qanday farq qiladi?",["Qurt mustaqil tarqaladi, virusga esa boshqa dastur kerak","Farq yo'q","Qurt zarar keltirmaydi","Virus mustaqil tarqaladi"],0),
("Ransomware (tovlamachilik dasturi) nima qiladi?",["Foydalanuvchi ma'lumotlarini shifrlaydi va ochish uchun to'lov talab qiladi","Ma'lumotlarni zaxiralaydi","Tizimni tezlashtiradi","Viruslarni aniqlaydi"],0),
("Spyware (josuslik dasturi) nima qiladi?",["Foydalanuvchi faoliyatini yashirincha kuzatadi va ma'lumotlarni uzatadi","Tizimni himoyalaydi","Tarmoq tezligini oshiradi","Fayllarni siqadi"],0),
("Rootkit nima?",["Tizimda yashirinib, administrator huquqlarini ega bo'lgan zararli dastur","Virusga qarshi dastur","Tarmoq protokoli","Ma'lumotlar bazasi"],0),
("Keylogger nima qiladi?",["Klaviaturadan kiritilgan barcha tugmachalarni yashirincha qayd qiladi","Ekranni yoritadi","Tovushni yozadi","Tarmoqni himoyalaydi"],0),
("Viruslarni aniqlashning signatura (imzo) usuli qanday ishlaydi?",["Ma'lum viruslarning noyob kod namunalari bilan solishtirish orqali","Tasodifiy tekshirish","Faqat fayl nomini tekshirish","Faqat fayl hajmini tekshirish"],0),
("Viruslarni aniqlashning evristik usuli qanday ishlaydi?",["Dasturning shubhali xatti-harakatlarini tahlil qilish orqali","Faqat signatura bo'yicha","Faqat fayl nomini tekshirish","Faqat internetni tekshirish"],0),
("Antivirus dasturining asosiy vazifasi:",["Zararli dasturlarni aniqlash, bloklash va yo'q qilish","Tarmoq tezligini oshirish","Ma'lumotlarni shifrlash","Fayllarni siqish"],0),
("Adware nima?",["Foydalanuvchiga ruxsatsiz reklama ko'rsatadigan dastur","Virusga qarshi dastur","Foydali dastur","Operatsion tizim"],0),
("Polimorf virus nima?",["Har safar ko'payishda o'z kodini o'zgartirib, aniqlashni qiyinlashtiruvchi virus","Oddiy virus","Foydali dastur","Tarmoq protokoli"],0),
("Ijtimoiy injineriya (social engineering) nima?",["Insonlar psixologiyasini ishlatib, maxfiy ma'lumotlarni olish usuli","Dasturlash usuli","Tarmoq sozlash usuli","Kompyuter ta'mirlash usuli"],0),
("Fishing (phishing) hujumi nima?",["Qalbaki xabarlar orqali foydalanuvchidan maxfiy ma'lumotlarni olishga urinish","Baliq ovlash","Tarmoq hujumi","Virus tarqatish"],0),
("Spear phishing oddiy phishingdan qanday farq qiladi?",["Aniq bir shaxs yoki tashkilotni nishonga olgan maqsadli hujum","Farq yo'q","Kamroq xavfli","Faqat telefon orqali"],0),
("Vishing nima?",["Telefon qo'ng'irog'i orqali amalga oshiriladigan fishing hujumi","Elektron pochta orqali hujum","SMS orqali hujum","Veb sayt orqali hujum"],0),
("Smishing nima?",["SMS xabarlar orqali amalga oshiriladigan fishing hujumi","Telefon qo'ng'irog'i orqali hujum","Elektron pochta orqali hujum","Veb sayt orqali hujum"],0),
]

data = []
for q_text, opts, correct_idx in Q:
    data.append({"question": q_text, "options": opts, "correct_id": correct_idx})

with open("questions.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"questions.json yaratildi: {len(data)} ta savol")
